import { TextItem } from './TextItem';

export class ComboBoxItem extends TextItem {
    static ISC_CLASS_NAME = 'ComboBoxItem';
    
    static IS_CLASS = true;
static PROPERTY_TYPES = {"pickerExitButtonProperties":{"className":"NavigationButton","isProperties":true},"completeOnEnter":"Boolean","sortField":["String",{"className":"String","isArray":true},"Integer"],"separateValuesListProperties":{"className":"ListGrid","isProperties":true},"filterLocally":"Boolean","useClientFiltering":"Boolean","pickListCriteria":{"className":"Criteria"},"pickerSaveButtonProperties":{"className":"NavigationButton","isProperties":true},"addUnknownValues":"Boolean","maskSaveLiterals":"boolean","pickerSearchFieldProperties":{"className":"TextItem","isProperties":true},"showHintInField":"boolean","fetchDisplayedFieldsOnly":"boolean","minimumSearchLength":"Integer","allowExpressions":"boolean","defaultValue":"Any","initialSort":{"className":"SortSpecifier","isArray":true},"optionDataSource":[{"className":"DataSource"},"String"],"showPickerSearchIcon":"Boolean","progressiveLoading":"Boolean","showPickListOnKeypress":"Boolean","pickListPlacement":["PanelPlacement",{"className":"Canvas"},"String"],"pickerIconHeight":"int","separateSpecialValues":"boolean","pickerSearchIconProperties":{"className":"FormItemIcon","isProperties":true},"filterFields":{"className":"String","isArray":true},"pickerClearButtonProperties":{"className":"NavigationButton","isProperties":true},"rootNodeId":["String","Number"],"filterWithValue":"boolean","showOptionsFromDataSource":"boolean","defaultToFirstOption":"Boolean","specialValues":{"className":"ValueMap"},"pickerSearchFormProperties":{"className":"DynamicForm","isProperties":true},"saveOnEnter":"Boolean","showAllOptions":"boolean","pickerSearchIconSize":"Integer","optionFilterContext":{"className":"DSRequest","isProperties":true},"showPickerIcon":"Boolean","completeOnTab":"Boolean","singleClickFolderToggle":"boolean","cachePickListResults":"boolean","pickerIconWidth":"int","generateExactMatchCriteria":"boolean","pickListProperties":{"className":"ListGrid","isProperties":true},"autoFetchData":"Boolean","formatOnBlur":"Boolean","allowEmptyValue":"Boolean","pickerNavigationBarProperties":{"className":"NavigationBar","isProperties":true},"pickListFields":{"className":"ListGridField","isArray":true},"maskOverwriteMode":"boolean"};

}
