import { Canvas } from './Canvas';

export class DynamicForm extends Canvas {
    static ISC_CLASS_NAME = 'DynamicForm';
    
    static IS_CLASS = true;
static PROPERTY_TYPES = {"checkFileAccessOnSubmit":"boolean","errorItemProperties":{"className":"Object","isProperties":true},"clipItemTitles":"boolean","revertValueKey":{"className":"KeyIdentifier"},"canTabToIcons":"Boolean","showInlineErrors":"Boolean","showErrorIcons":"Boolean","minHintWidth":"Integer","linearAutoSpanItems":"Boolean","linearNumCols":"number","disableValidation":"boolean","showTitlesWithErrorMessages":"Boolean","showDetailFields":"Boolean","valuesManager":[{"className":"ValuesManager"},"GlobalId"],"wrapItemTitles":"boolean","showImageAsURL":"boolean","implicitSave":"Boolean","cellPadding":"number","canTabToSectionHeaders":"boolean","implicitSaveDelay":"number","synchronousValidation":"Boolean","userTask":{"className":"UserTask"},"validateOnExit":"Boolean","implicitSaveOnBlur":"Boolean","canFocus":"Boolean","colWidths":{"className":"String","isArray":true},"linearHintWidth":["Number","String"],"fields":{"className":"FormItem","isArray":true,"deepCopy":true},"suppressBrowserClearIcons":"boolean","itemHoverHeight":["Number","String"],"linearMode":"Boolean","allowExpressions":"boolean","clipStaticValue":"Boolean","storeDisplayValues":"Boolean","longTextEditorThreshold":"number","titleWidth":"number","minColWidth":"number","showErrorStyle":"Boolean","hiliteRequiredFields":"Boolean","canEdit":"Boolean","items":{"className":"FormItem","isArray":true},"linearOnMobile":"boolean","stopOnError":"boolean","suppressValidationErrorCallback":"Boolean","dataSource":{"className":"DataSource"},"showPending":"Boolean","itemHoverDelay":"number","selectOnFocus":"Boolean","rejectInvalidValueOnChange":"boolean","values":{"className":"Object"},"autoFocusOnError":"Boolean","fixedColWidths":"Boolean","itemHoverWidth":["Number","String"],"implicitCriteria":{"className":"Criteria"},"initialCriteria":{"className":"Criteria"},"errors":{"className":"Object"},"selectOnClick":"Boolean","itemHoverVAlign":["Number","String"],"saveOnEnter":"Boolean","showDeletions":"Boolean","autoFetchData":"boolean","initialSort":{"className":"SortSpecifier","isArray":true},"cellBorder":"number","showComplexFieldsRecursively":"Boolean","showErrorText":"Boolean","autoFocus":"Boolean","showOldValueInHover":"Boolean","validateOnChange":"Boolean","fetchRequestProperties":{"className":"DSRequest","isProperties":true},"numCols":"number","wrapHintText":"Boolean","itemHoverOpacity":"number","browserSpellCheck":"Boolean","canSubmit":"Boolean"};
static CHILD_TYPE_MAPPING = {"FormItem":"fields","DataSource":"dataSource"};

}
