import { FormItem } from './FormItem';

export class SelectItem extends FormItem {
    static ISC_CLASS_NAME = 'SelectItem';
    
    static IS_CLASS = true;
static PROPERTY_TYPES = {"fetchDisplayedFieldsOnly":"boolean","showFocused":"Boolean","pickButtonWidth":"number","pickListFields":{"className":"ListGridField","isArray":true},"filterLocally":"Boolean","pickerNavigationBarProperties":{"className":"NavigationBar","isProperties":true},"showHintInField":"boolean","optionFilterContext":{"className":"DSRequest","isProperties":true},"cachePickListResults":"Boolean","pickListPlacement":["PanelPlacement",{"className":"Canvas"},"String"],"addUnknownValues":"Boolean","openOnSpace":"Boolean","rootNodeId":["String","Number"],"initialSort":{"className":"SortSpecifier","isArray":true},"singleClickFolderToggle":"boolean","defaultToFirstOption":"Boolean","escapeHTML":"Boolean","pickerIconWidth":"int","pickerClearButtonProperties":{"className":"NavigationButton","isProperties":true},"optionDataSource":[{"className":"DataSource"},"String"],"pickerExitButtonProperties":{"className":"NavigationButton","isProperties":true},"showOptionsFromDataSource":"boolean","updateControlOnOver":"Boolean","saveOnEnter":"Boolean","autoFetchData":"Boolean","pickListProperties":{"className":"ListGrid","isProperties":true},"pickListCriteria":{"className":"Criteria"},"progressiveLoading":"boolean","defaultValue":"Any","sortField":["String",{"className":"String","isArray":true},"Integer"],"canSelectText":"boolean","specialValues":{"className":"ValueMap"},"allowEmptyValue":"Boolean","height":"number","updateTextBoxOnOver":"Boolean","useClientFiltering":"Boolean","separateValuesListProperties":{"className":"ListGrid","isProperties":true},"separateSpecialValues":"boolean","pickerIconHeight":"int","showPickerIcon":"Boolean","allowMultiCharSearch":"boolean","openOnDownArrow":"Boolean","hiliteOnFocus":"boolean","showOver":"boolean","pickButtonHeight":"number","multiple":"Boolean"};

}
