import { ListGrid } from './ListGrid';

export class TreeGrid extends ListGrid {
    static ISC_CLASS_NAME = 'TreeGrid';
    
    static IS_CLASS = true;
static PROPERTY_TYPES = {"useAllDataSourceFields":"boolean","openerIconSize":"number","canReorderRecords":"Boolean","showSelectedIcons":"Boolean","groupByField":["String",{"className":"String","isArray":true}],"showFullConnectors":"Boolean","iconSize":"number","createDefaultTreeField":"Boolean","extraIconGap":"int","iconPadding":"Integer","canAcceptDroppedRecords":"Boolean","showFolderIcons":"Boolean","openerImage":["SCImgURL",{"className":"SCStatefulImgConfig"}],"initialData":{"className":"TreeNode","isArray":true},"showRoot":"Boolean","showDisabledSelectionCheckbox":"Boolean","keepParentsOnFilter":"boolean","canSelectAll":"boolean","openerIconHeight":"number","treeRootValue":"Any","autoAssignTreeField":"boolean","connectorImage":["SCImgURL",{"className":"SCStatefulImgConfig"}],"showCustomIconDrop":"Boolean","showNodeIcons":"Boolean","canReparentNodes":"boolean","cascadeSelection":"Boolean","animateFolderSpeed":"number","showCustomIconSelected":"Boolean","leaveSelectionCheckboxGap":"Boolean","animateFolderMaxRows":"Integer","canDragRecordsOut":"Boolean","separateFolders":"boolean","canDropOnLeaves":"Boolean","indentRecordComponents":"Boolean","animateFolderTime":"number","serverFilterFields":{"className":"String","isArray":true},"showDropEndSpace":"boolean","data":{"className":"Tree"},"showConnectors":"Boolean","sortFoldersBeforeLeaves":"boolean","showLoadingIcons":"boolean","openIconPadding":"Integer","showOpener":"Boolean","openerIconWidth":"number","canDropSiblingAfterLastNode":"boolean","showSelectedOpener":"Boolean","showDropIcons":"Boolean","alwaysShowOpener":"Boolean","dropEndSpace":"Integer","loadDataOnDemand":"boolean","showCustomIconOpen":"Boolean","treeFieldMinWidth":"Number","animateFolders":"Boolean","showPartialSelection":"Boolean","fields":{"className":"TreeGridField","isArray":true},"folderIconPadding":"Integer","dataProperties":{"className":"Tree","isProperties":true},"dataSource":{"className":"DataSource"},"saveOpenStateInViewState":"Boolean","indentSize":"number","showOpenIcons":"Boolean"};
static CHILD_TYPE_MAPPING = {"TreeGridField":"fields","DataSource":"dataSource"};

}
