import { Field } from './Field';

export class DataSourceField extends Field {
    IS_A_VIRTUAL_COMPONENT = true;

    static IS_CLASS = false;
static PROPERTY_TYPES = {"autoGenerated":"boolean","canSortClientOnly":"boolean","valueMap":{"className":"ValueMap"},"initRequiresAuthentication":"boolean","required":"boolean","escapeHTML":"Boolean","updateRequiresAuthentication":"boolean","creatorOverrides":"boolean","batchUploadCaseSensitive":"Boolean","canExport":"Boolean","imageWidth":["number","String"],"exportForceText":"boolean","sqlForceInsensitive":"Boolean","storeMilliseconds":"Boolean","canEdit":"boolean","showFileInline":"boolean","recreateOnChange":"Boolean","deepCloneOnEdit":"Boolean","excludeFromState":"Boolean","canView":"boolean","viewRequiresAuthentication":"boolean","validOperators":{"className":"OperatorId","isArray":true},"customSQL":"boolean","hidden":"boolean","inapplicable":"boolean","decimalPrecision":"number","primaryKey":"boolean","allowClientRequestedSummaries":"boolean","validators":{"className":"Validator","isArray":true},"autoQuoteCustomExpressions":"boolean","xmlAttribute":"boolean","length":"number","ignore":"boolean","canSave":"boolean","editRequiresAuthentication":"boolean","maxFileSize":"Integer","useLocalDisplayFieldValue":"Boolean","skipTypeCoercion":"boolean","rootValue":"Any","stringInBrowser":"Boolean","canFilter":"boolean","ignoreTextMatchStyle":"Boolean","nullReplacementValue":"Any","imageHeight":["number","String"],"calculated":"Boolean","implicitSequence":"Boolean","decimalPad":"number","nillable":"boolean","encodeInResponse":"boolean","imageSize":["number","String"],"precision":"number","childrenProperty":"Boolean","multiple":"Boolean","lenientXPath":"boolean","detail":"boolean","propertiesOnly":"boolean"};

}
