import { VLayout } from './VLayout';

export class DateChooser extends VLayout {
    static ISC_CLASS_NAME = 'DateChooser';
    
    static IS_CLASS = true;
static PROPERTY_TYPES = {"navigationButtonHeight":"Integer","previousYearButtonProperties":{"className":"IButton","isProperties":true},"showDoubleYearIcon":"boolean","timeItemProperties":{"className":"TimeItem","isProperties":true},"previousMonthButtonProperties":{"className":"IButton","isProperties":true},"headerHeight":"Integer","endDate":{"className":"Date"},"showTodayButton":"Boolean","alternateWeekStyles":"boolean","fiscalYearChooserButtonProperties":{"className":"IButton","isProperties":true},"nextMonthIconHeight":"int","weekendDays":{"className":"int","isArray":true},"dayNameLength":"number","nextYearIconWidth":"int","buttonLayoutProperties":{"className":"HLayout","isProperties":true},"showApplyButton":"Boolean","dateGridProperties":{"className":"DateGrid","isProperties":true},"showCancelButton":"Boolean","showTimeItem":"Boolean","navigationLayoutHeight":"int","nextYearIconHeight":"int","endYear":"int","showFiscalYearChooser":"Boolean","showWeekChooser":"Boolean","applyButtonProperties":{"className":"IButton","isProperties":true},"startDate":{"className":"Date"},"cancelButtonProperties":{"className":"IButton","isProperties":true},"prevMonthIconHeight":"int","navigationLayoutProperties":{"className":"HLayout","isProperties":true},"startYear":"int","startYearRange":"Integer","weekChooserButtonProperties":{"className":"IButton","isProperties":true},"disabledDates":{"className":"Date","isArray":true},"yearChooserButtonProperties":{"className":"IButton","isProperties":true},"endYearRange":"Integer","nextMonthButtonProperties":{"className":"IButton","isProperties":true},"styleWeekends":"Boolean","closeOnDateClick":"Boolean","buttonLayoutControls":{"className":"String","isArray":true},"todayButtonProperties":{"className":"IButton","isProperties":true},"monthChooserButtonProperties":{"className":"IButton","isProperties":true},"todayButtonHeight":"Integer","nextYearButtonProperties":{"className":"IButton","isProperties":true},"prevYearIconHeight":"int","showWeekends":"Boolean","prevMonthIconWidth":"int","use24HourTime":"Boolean","nextMonthIconWidth":"int","showSecondItem":"Boolean","closeOnEscapeKeypress":"boolean","disableWeekends":"Boolean","useFirstDayOfFiscalWeek":"Boolean","firstDayOfWeek":"int","prevYearIconWidth":"int"};

}
