import { ListGrid } from './ListGrid';

export class Menu extends ListGrid {
    static ISC_CLASS_NAME = 'Menu';
    
    static IS_CLASS = true;
static PROPERTY_TYPES = {"target":{"className":"Canvas"},"canSaveSearches":"boolean","submenuFieldDefaults":{"className":"ListGridField","isProperties":true},"submenuDisabledImage":["SCImgURL",{"className":"ImgHTMLProperties"}],"filterHiddenItems":"Boolean","fetchSubmenus":"Boolean","navigationBarProperties":{"className":"NavigationBar","isProperties":true},"iconWidth":"number","items":{"className":"MenuItem","isArray":true},"dataProperties":{"className":"Tree","isProperties":true},"submenuImage":["SCImgURL",{"className":"ImgHTMLProperties"}],"initialCriteria":{"className":"Criteria"},"useKeys":"Boolean","showSubmenus":"Boolean","iconFieldProperties":{"className":"ListGridField","isProperties":true},"canShowFilterEditor":"boolean","showEdges":"Boolean","autoFetchData":"boolean","cellHeight":"number","navStackProperties":{"className":"Canvas","isProperties":true},"iconHeight":"number","defaultWidth":"int","canSelectParentItems":"boolean","fields":[{"className":"MenuFieldID","isArray":true},{"className":"ListGridField","isArray":true}],"showShadow":"Boolean","cascadeAutoDismiss":"Boolean","autoDraw":"Boolean","showIcons":"Boolean","data":[{"className":"MenuItem","isArray":true},{"className":"Tree"}],"autoDismiss":"Boolean","dataSource":{"className":"DataSource"},"keyFieldProperties":{"className":"ListGridField","isProperties":true},"alternateRecordStyles":"Boolean","checkmarkDisabledImage":["SCImgURL",{"className":"ImgHTMLProperties"}],"iconFieldDefaults":{"className":"ListGridField","isProperties":true},"showKeys":"Boolean","keyFieldDefaults":{"className":"ListGridField","isProperties":true},"menuButtonWidth":"int","autoDismissOnBlur":"Boolean","titleFieldDefaults":{"className":"ListGridField","isProperties":true},"submenuFieldProperties":{"className":"ListGridField","isProperties":true},"titleFieldProperties":{"className":"ListGridField","isProperties":true},"checkmarkImage":["SCImgURL",{"className":"ImgHTMLProperties"}]};
static CHILD_TYPE_MAPPING = {"MenuFieldID":"fields","DataSource":"dataSource","MenuItem":"data"};

}
