import { ILogicalComponent } from './core/ILogicalComponent';

export class OperationBinding extends ILogicalComponent {
    static ISC_CLASS_NAME = 'OperationBinding';

    static IS_CLASS = true;
static PROPERTY_TYPES = {"preventHTTPCaching":"boolean","qualifyColumnNames":"boolean","customValueFields":["String",{"className":"String","isArray":true}],"groupBy":{"className":"String","isArray":true},"mail":{"className":"Mail"},"requiresAuthentication":"boolean","useHavingClause":"boolean","criteria":{"className":"DSRequestModifier","isArray":true},"useHttpProxy":"boolean","exportResults":"boolean","serverObject":{"className":"ServerObject"},"requestProperties":{"className":"DSRequest","isProperties":true},"summaryFunctions":{"className":"Object"},"customCriteriaFields":["String",{"className":"String","isArray":true}],"excludeCriteriaFields":["String",{"className":"String","isArray":true}],"xmlNamespaces":{"className":"Object"},"useForCacheSync":"boolean","creatorOverrides":"boolean","sqlSuffix":["VelocityExpression","String"],"suppressAutoMappings":"Boolean","customFields":["String",{"className":"String","isArray":true}],"multiInsertBatchSize":"Integer","exportFields":{"className":"String","isArray":true},"responseDataSchema":{"className":"DataSource"},"allowAdvancedCriteria":"boolean","invalidateCache":"boolean","useFlatFields":"boolean","canSyncCache":"Boolean","autoJoinTransactions":"boolean","progressiveLoading":"boolean","useSpringTransaction":"boolean","skipRowCount":"boolean","wrapInList":"Boolean","useSubselectForRowCount":"boolean","includeAnsiJoinsInTableClause":"boolean","isDDL":"Boolean","transformMultipleFields":"boolean","skipAudit":"boolean","applyCriteriaBeforeAggregation":"boolean","defaultParams":{"className":"Object"},"values":{"className":"DSRequestModifier","isArray":true},"makeKeysAvailable":"Boolean","allowMultiUpdate":"boolean","spoofResponses":"boolean","sqlUsePagingHint":"boolean","sqlPrefix":["VelocityExpression","String"],"providesMissingKeys":"boolean","arrayCriteriaForceExact":"Boolean"};

}
