import { Layout } from './Layout';

export class Window extends Layout {
    static ISC_CLASS_NAME = 'Window';
    
    static IS_CLASS = true;
static PROPERTY_TYPES = {"isModal":"Boolean","restoreButtonProperties":{"className":"ImgButton","isProperties":true},"maximizeButtonProperties":{"className":"ImgButton","isProperties":true},"headerControls":{"className":"String","isArray":true},"headerBackgroundProperties":{"className":"Img","isProperties":true},"headerIconProperties":{"className":"Img","isProperties":true},"dismissOnEscape":"Boolean","bodyProperties":{"className":"Canvas","isProperties":true},"showHeaderBackground":"Boolean","headerProperties":{"className":"HLayout","isProperties":true},"footerControls":{"className":"String","isArray":true},"animateMinimize":"boolean","defaultMinimizeHeight":"number","canDragResize":"Boolean","resizerProperties":{"className":"ImgButton","isProperties":true},"useBackMask":"Boolean","keepInParentRect":["Boolean",{"className":"Integer","isArray":true}],"showModalMask":"boolean","dismissOnOutsideClick":"Boolean","showFooter":"Boolean","showMaximizeButton":"Boolean","canDragReposition":"Boolean","statusBarProperties":{"className":"Canvas","isProperties":true},"headerLabelProperties":{"className":"Label","isProperties":true},"minimizeTime":"number","headerLabelDefaults":{"className":"Object"},"closeButtonProperties":{"className":"ImgButton","isProperties":true},"showStatusBar":"Boolean","showShadow":"Boolean","showTitle":"Boolean","showBody":"Boolean","showHeader":"Boolean","modalMaskProperties":{"className":"Canvas","isProperties":true},"maximized":"Boolean","bringToFrontOnMouseUp":"boolean","showResizer":"Boolean","headerIconDefaults":{"className":"Object"},"minimizeButtonProperties":{"className":"ImgButton","isProperties":true},"bodyDefaults":{"className":"Object"},"canFocusInHeaderButtons":"Boolean","minimizeHeight":"number","footerProperties":{"className":"HLayout","isProperties":true},"footerHeight":"number","minimized":"Boolean","showHeaderIcon":"Boolean","showCloseButton":"Boolean","resizeFrom":{"className":"EdgeName","isArray":true},"modalMaskOpacity":"number","showMinimizeButton":"Boolean","showEdges":"Boolean","opacity":"Integer","items":[{"className":"Canvas","isArray":true},{"className":"Canvas"},"String"],"autoSize":"Boolean","autoCenter":"Boolean"};

}
