/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.42
 * Generated at: 2025-06-20 02:55:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.examples.databinding;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class tree_005fdatabinding_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/isomorphic_core_rpc.jar", Long.valueOf(1750169604742L));
    _jspx_dependants.put("jar:file:/C:/Users/User/Downloads/SmartClient_v141p_2025-06-14_Evaluation/SmartClient_v141p_2025-06-14_Evaluation/smartclientSDK/WEB-INF/lib/isomorphic_core_rpc.jar!/META-INF/isc.tld", Long.valueOf(1749892736000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fisomorphic_005floadISC_0026_005fskin_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fisomorphic_005floadDS_0026_005fID_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fisomorphic_005floadISC_0026_005fskin_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fisomorphic_005floadDS_0026_005fID_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fisomorphic_005floadISC_0026_005fskin_005fnobody.release();
    _005fjspx_005ftagPool_005fisomorphic_005floadDS_0026_005fID_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--------------------------------------------------------------------\n");
      out.write("	SmartClient SDK\n");
      out.write("	Tree Data Binding example\n");
      out.write("\n");
      out.write("	Copyright 2001 and beyond Isomorphic Software, Inc. (www.isomorphic.com)\n");
      out.write("---------------------------------------------------------------------->\n");
      out.write("\n");
      out.write("\n");
      out.write("<HEAD><TITLE>\n");
      out.write("		SmartClient SDK - Tree Data Binding example\n");
      out.write("</TITLE>");
      if (_jspx_meth_isomorphic_005floadISC_005f0(_jspx_page_context))
        return;
      out.write("</HEAD>\n");
      out.write("<BODY BGCOLOR=#D3D3D3><SCRIPT>\n");
      out.write("\n");
      out.write("\n");
      out.write("// load datasource\n");
      if (_jspx_meth_isomorphic_005floadDS_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("// create treeGrid bound to this datasource\n");
      out.write("TreeGrid.create({\n");
      out.write("	ID:\"employeeTree\",\n");
      out.write("	left:50, top:50, width:700, height:500,\n");
      out.write("	dataSource:\"employees\",\n");
      out.write("	fields:[\n");
      out.write("		{name:\"Name\", treeField:true},\n");
      out.write("		{name:\"Job\"},\n");
      out.write("		{name:\"Email\"}\n");
      out.write("	]\n");
      out.write("});\n");
      out.write("\n");
      out.write("\n");
      out.write("// fetch top-level nodes to populate treeGrid\n");
      out.write("employeeTree.fetchData();\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</SCRIPT>\n");
      out.write("</BODY></HTML>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_isomorphic_005floadISC_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  isomorphic:loadISC
    com.isomorphic.taglib.LoadISCTag _jspx_th_isomorphic_005floadISC_005f0 = (com.isomorphic.taglib.LoadISCTag) _005fjspx_005ftagPool_005fisomorphic_005floadISC_0026_005fskin_005fnobody.get(com.isomorphic.taglib.LoadISCTag.class);
    _jspx_th_isomorphic_005floadISC_005f0.setPageContext(_jspx_page_context);
    _jspx_th_isomorphic_005floadISC_005f0.setParent(null);
    // /examples/databinding/tree_databinding.jsp(11,8) name = skin type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_isomorphic_005floadISC_005f0.setSkin("SmartClient");
    int _jspx_eval_isomorphic_005floadISC_005f0 = _jspx_th_isomorphic_005floadISC_005f0.doStartTag();
    if (_jspx_th_isomorphic_005floadISC_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fisomorphic_005floadISC_0026_005fskin_005fnobody.reuse(_jspx_th_isomorphic_005floadISC_005f0);
    return false;
  }

  private boolean _jspx_meth_isomorphic_005floadDS_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  isomorphic:loadDS
    com.isomorphic.taglib.LoadDSTag _jspx_th_isomorphic_005floadDS_005f0 = (com.isomorphic.taglib.LoadDSTag) _005fjspx_005ftagPool_005fisomorphic_005floadDS_0026_005fID_005fnobody.get(com.isomorphic.taglib.LoadDSTag.class);
    _jspx_th_isomorphic_005floadDS_005f0.setPageContext(_jspx_page_context);
    _jspx_th_isomorphic_005floadDS_005f0.setParent(null);
    // /examples/databinding/tree_databinding.jsp(16,0) name = ID type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_isomorphic_005floadDS_005f0.setID("employees");
    int _jspx_eval_isomorphic_005floadDS_005f0 = _jspx_th_isomorphic_005floadDS_005f0.doStartTag();
    if (_jspx_th_isomorphic_005floadDS_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fisomorphic_005floadDS_0026_005fID_005fnobody.reuse(_jspx_th_isomorphic_005floadDS_005f0);
    return false;
  }
}
